// pump is iam analytics purger that moves the data generated by your iam-authz-server nodes to any back-end.
// It is primarily used to display your analytics data in the iam operating system.
package main

import (
	"math/rand"
	"time"

	_ "go.uber.org/automaxprocs"

	_ "go.uber.org/automaxprocs"

	"github.com/marmotedu/iam/internal/pump"
)

func main() {
	rand.Seed(time.Now().UTC().UnixNano())

	pump.NewApp("iam-pump").Run()
}
